-- INLINE VIEW 실습

/*
 *  2005년에 입사한 사원들의 부서명과 이름을 조회
 */

SELECT D.DEPARTMENT_NAME 
	 , E_2005.FIRST_NAME
  FROM (SELECT E.FIRST_NAME
  			 , E.DEPARTMENT_ID
  		  FROM EMPLOYEES E
  		 WHERE E.HIRE_DATE BETWEEN TO_DATE('2005.01/01','YY/MM/DD') AND TO_DATE('2005.12.31','YY/MM/DD')) E_2005
  JOIN DEPARTMENTS D
  	ON D.DEPARTMENT_ID = E_2005.DEPARTMENT_ID
;  
/*
 * 연봉을 많이 받는 사람들 중 상위 10명의 이름과 부서명을 조회
 */
  	
SELECT E_TOP10.FIRST_NAME
	 , D.DEPARTMENT_NAME 
  FROM (SELECT E.FIRST_NAME
  			 , E.DEPARTMENT_ID
  		  FROM EMPLOYEES E
  		 ORDER BY E.SALARY DESC) E_TOP10
  JOIN DEPARTMENTS D 
  	ON D.DEPARTMENT_ID = E_TOP10.DEPARTMENT_ID
  WHERE ROWNUM <= 10
;


/*
 * 이름으로 내림차순 정렬된 데이터 중 상위 20개의 사원번호, 이름, 부서명을 조회
 */

SELECT E_TOP20.EMPLOYEE_ID 
 	 , E_TOP20.FIRST_NAME
	 , D.DEPARTMENT_NAME 
  FROM (SELECT EMPLOYEE_ID
  			 , FIRST_NAME
  			 , DEPARTMENT_ID
  		  FROM EMPLOYEES
  		 ORDER BY FIRST_NAME DESC) E_TOP20
  JOIN DEPARTMENTS D
  	ON D.DEPARTMENT_ID = E_TOP20.DEPARTMENT_ID
  WHERE ROWNUM <= 20
;

/*
 * 사원수가 가장 많은 부서의 사원명, 부서명을 조회
 */

SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 WHERE D.DEPARTMENT_ID = (SELECT *
				  		    FROM (SELECT DEPARTMENT_ID
					  	  		    FROM EMPLOYEES
					 			   GROUP BY DEPARTMENT_ID
					 		  	   ORDER BY COUNT(1) DESC) 
						   WHERE ROWNUM =1)

SELECT E.FIRST_NAME 
	 , D_MAX.DEPARTMENT_NAME
  FROM (SELECT D.DEPARTMENT_ID
	 		 , D.DEPARTMENT_NAME 
  		  FROM (SELECT DEPARTMENT_ID
	  			  FROM EMPLOYEES
	 			 GROUP BY DEPARTMENT_ID
	 			 ORDER BY COUNT(1) DESC) D_MAX
		  JOIN DEPARTMENTS D 
		 	ON D.DEPARTMENT_ID = D_MAX.DEPARTMENT_ID
		 WHERE ROWNUM =1) D_MAX
  JOIN EMPLOYEES E 
  	ON E.DEPARTMENT_ID = D_MAX.DEPARTMENT_ID
;


 



  
  
  
  
  