/*
 * 도시, 부서명, 이름, 성 조회
 */

SELECT L.CITY 
	 , D.DEPARTMENT_NAME 
	 , E.FIRST_NAME 
	 , E.LAST_NAME
  FROM LOCATIONS L
  INNER JOIN DEPARTMENTS D 
 	ON L.LOCATION_ID = D.LOCATION_ID
  RIGHT OUTER JOIN EMPLOYEES E 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
;

/*
 * 국가 'Canada'에서 근무하는 사원의 이름과 부서명을 조회
 */

SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L 
 	ON L.LOCATION_ID = D.LOCATION_ID
 INNER JOIN COUNTRIES C 
 	ON L.COUNTRY_ID = C.COUNTRY_ID
 WHERE C.COUNTRY_NAME = 'Canada'
;

/*
 * 1. 'SA_REP' 직무인 사원의 이름, 성, 연봉, 부서명, 직무명을 조회
 */

SELECT E.FIRST_NAME
	 , E.LAST_NAME 
	 , E.SALARY 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON E.JOB_ID =J.JOB_ID 
 WHERE J.JOB_ID = 'SA_REP'
; 	

/*
 * 2. 'MK_REP' 직무엿던 사원의 이름, 성, 연봉, 부서명, 현재 직무명을 조회
 */

SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 INNER JOIN JOB_HISTORY JH
 	ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID 
 WHERE JH.JOB_ID = 'MK_REP'
; 

/*
 * 3. 'New Jersey' 주에서 근무중인 사원의 이름, 부서명, 연봉을 조회
 */

SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , E.SALARY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 WHERE D.LOCATION_ID = (SELECT L.LOCATION_ID
 						  FROM LOCATIONS L
 						 WHERE L.STATE_PROVINCE = 'New Jersey')
 ;
 
/*
 * 4. 'C'로 시작하는 도시에서 근무중인 사원의 이름, 부서명, 직무명, 도시명을 조회
 */

SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON J.JOB_ID = E.JOB_ID 
 INNER JOIN LOCATIONS L 
 	ON L.LOCATION_ID = D.LOCATION_ID 
 WHERE L.CITY LIKE ('C%')
;

 /*
 * 5. 우편번호에 '7' 이 포함된 도시에서 근무중인 사원들의 사원번호, 직무명을 조회
 */

SELECT E.EMPLOYEE_ID 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON J.JOB_ID = E.JOB_ID 
 WHERE E.DEPARTMENT_ID IN (SELECT D.DEPARTMENT_ID
 							FROM DEPARTMENTS D
 						   WHERE D.LOCATION_ID IN (SELECT L.LOCATION_ID 
 						   							FROM LOCATIONS L
 						   						   WHERE L.POSTAL_CODE LIKE '%7%'))
;

/*
 * 6. 회사 전체 평균연봉보다 많은 연봉을 받는 사원들의 이름과 부서명을 조회
 */
 						   						   
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 WHERE E.SALARY > 	(SELECT AVG(E2.SALARY)
 					   FROM EMPLOYEES E2)
;

/*
 * 'Asia'에서 근무중인 사원들의 사원번호, 이름, 성, 부서명, 직무명, 도시명 조회
 */

SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON J.JOB_ID = E.JOB_ID 
 INNER JOIN LOCATIONS L 
 	ON L.LOCATION_ID = D.LOCATION_ID 
 WHERE L.COUNTRY_ID IN (SELECT C.COUNTRY_ID 
 						  FROM COUNTRIES C
 						 WHERE C.REGION_ID IN (SELECT R.REGION_ID
 						 						 FROM REGIONS R
 						 						WHERE R.REGION_NAME ='Asia'))
;

/*
 * 사원의 이름과 부서명을 조회
 * 부서에 포함되어 있거나 포함되지 않은 사원도 모두 조회
 */

SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D 
  	ON D.DEPARTMENT_ID =E.DEPARTMENT_ID  
;

/*
 * 부서별 사원의 이름
 */

SELECT D.DEPARTMENT_NAME 
	 , E.FIRST_NAME 
  FROM DEPARTMENTS D
  LEFT JOIN EMPLOYEES E 
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;


/*
 * 부서별 사원의 수
 * 
 */

SELECT D.DEPARTMENT_NAME 
	 , E.FIRST_NAME 
  FROM DEPARTMENTS D
  FULL JOIN EMPLOYEES E 
  	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
  	


/*
 * 모든 도시에 위치한 부서를 조회
 */

SELECT L.CITY 
	 , D.*
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D 
  	ON L.LOCATION_ID = D.LOCATION_ID 
;


/*
 * 모든 도시의 도시별 부서의 개수를 조회
 * 도시명 | 부서 개수
 */

SELECT L.CITY 
	 , COUNT(D.DEPARTMENT_ID)
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D 
  	ON L.LOCATION_ID = D.LOCATION_ID 
 GROUP BY L.CITY 
;

/*
 * 국가별 지역
 */

SELECT C.COUNTRY_NAME 
	 , L.*
  FROM COUNTRIES C
  LEFT OUTER JOIN LOCATIONS L 
  	ON L.COUNTRY_ID = C.COUNTRY_ID
;

/*
 * 국가별 지역의 개수
 */

SELECT C.COUNTRY_NAME 
	 , COUNT(L.LOCATION_ID)
  FROM COUNTRIES C
  LEFT OUTER JOIN LOCATIONS L 
  	ON L.COUNTRY_ID = C.COUNTRY_ID
 GROUP BY C.COUNTRY_NAME
;

/*
 * 직무별 사원의 수를 조회
 */

SELECT J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID)
  FROM JOBS J
  LEFT JOIN EMPLOYEES E 
  	ON E.JOB_ID = J.JOB_ID 
 GROUP BY J.JOB_TITLE 
;


/*
 * 직무별 사원의 수를 조회
 * 단, 사원의 수가 5명 이상인 직무만 조회
 */
  	
SELECT J.JOB_TITLE
	 , COUNT(1)
  FROM JOBS J
  LEFT JOIN EMPLOYEES E
  	ON E.JOB_ID = J.JOB_ID 
  GROUP BY J.JOB_TITLE 
  HAVING COUNT(1) >= 5
;

/*
 * 사원이 단 한명도 없는 부서명을 조회
 */

SELECT D.DEPARTMENT_NAME
  FROM DEPARTMENTS D
  LEFT JOIN EMPLOYEES E 
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE E.EMPLOYEE_ID IS NULL
;
  
/*
 * 대륙별 지역의 수를 조회
 */

SELECT R.REGION_NAME 
	 , COUNT(L.LOCATION_ID)
  FROM REGIONS R
  JOIN COUNTRIES C 
  	ON C.REGION_ID = R.REGION_ID 
  LEFT JOIN LOCATIONS L 
  	ON L.COUNTRY_ID = C.COUNTRY_ID 
 GROUP BY R.REGION_NAME 
;

/*
 * 도시별 사원의 수를 조회
 */
 
SELECT L.CITY  
	 , COUNT(E.EMPLOYEE_ID)
  FROM LOCATIONS L
  LEFT JOIN DEPARTMENTS D 
  	ON D.LOCATION_ID = L.LOCATION_ID 
  LEFT JOIN EMPLOYEES E 
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
  GROUP BY L.CITY 
;

