/*
 * 도시, 부서명, 이름, 성 조회
 */

SELECT L.CITY 
	 , D.DEPARTMENT_NAME 
	 , E.FIRST_NAME 
	 , E.LAST_NAME
  FROM LOCATIONS L
  INNER JOIN DEPARTMENTS D 
 	ON L.LOCATION_ID = D.LOCATION_ID
  RIGHT OUTER JOIN EMPLOYEES E 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
;

/*
 * 국가 'Canada'에서 근무하는 사원의 이름과 부서명을 조회
 */

SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L 
 	ON L.LOCATION_ID = D.LOCATION_ID
 INNER JOIN COUNTRIES C 
 	ON L.COUNTRY_ID = C.COUNTRY_ID
 WHERE C.COUNTRY_NAME = 'Canada'
;

/*
 * 1. 'SA_REP' 직무인 사원의 이름, 성, 연봉, 부서명, 직무명을 조회
 */

SELECT E.FIRST_NAME
	 , E.LAST_NAME 
	 , E.SALARY 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON E.JOB_ID =J.JOB_ID 
 WHERE J.JOB_ID = 'SA_REP'
; 	

/*
 * 2. 'MK_REP' 직무엿던 사원의 이름, 성, 연봉, 부서명, 현재 직무명을 조회
 */

SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 INNER JOIN JOB_HISTORY JH
 	ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID 
 WHERE JH.JOB_ID = 'MK_REP'
; 

/*
 * 3. 'New Jersey' 주에서 근무중인 사원의 이름, 부서명, 연봉을 조회
 */

SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , E.SALARY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 WHERE D.LOCATION_ID = (SELECT L.LOCATION_ID
 						  FROM LOCATIONS L
 						 WHERE L.STATE_PROVINCE = 'New Jersey')
 ;
 
/*
 * 4. 'C'로 시작하는 도시에서 근무중인 사원의 이름, 부서명, 직무명, 도시명을 조회
 */

SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON J.JOB_ID = E.JOB_ID 
 INNER JOIN LOCATIONS L 
 	ON L.LOCATION_ID = D.LOCATION_ID 
 WHERE L.CITY LIKE ('C%')
;

 /*
 * 5. 우편번호에 '7' 이 포함된 도시에서 근무중인 사원들의 사원번호, 직무명을 조회
 */

SELECT E.EMPLOYEE_ID 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON J.JOB_ID = E.JOB_ID 
 WHERE E.DEPARTMENT_ID IN (SELECT D.DEPARTMENT_ID
 							FROM DEPARTMENTS D
 						   WHERE D.LOCATION_ID IN (SELECT L.LOCATION_ID 
 						   							FROM LOCATIONS L
 						   						   WHERE L.POSTAL_CODE LIKE '%7%'))
;

/*
 * 6. 회사 전체 평균연봉보다 많은 연봉을 받는 사원들의 이름과 부서명을 조회
 */
 						   						   
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 WHERE E.SALARY > 	(SELECT AVG(E2.SALARY)
 					   FROM EMPLOYEES E2)
;

/*
 * 'Asia'에서 근무중인 사원들의 사원번호, 이름, 성, 부서명, 직무명, 도시명 조회
 */

SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON J.JOB_ID = E.JOB_ID 
 INNER JOIN LOCATIONS L 
 	ON L.LOCATION_ID = D.LOCATION_ID 
 WHERE L.COUNTRY_ID IN (SELECT C.COUNTRY_ID 
 						  FROM COUNTRIES C
 						 WHERE C.REGION_ID IN (SELECT R.REGION_ID
 						 						 FROM REGIONS R
 						 						WHERE R.REGION_NAME ='Asia'))
;






