-- EXISTS (FULL SCAN 해서 성능 구림)

-- 사원이 있는 부서를 조회
SELECT *
  FROM DEPARTMENTS D
 WHERE EXISTS (SELECT 1
 				 FROM EMPLOYEES E
 				WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
;

-- 사원이 없는 부서를 조회
SELECT *
  FROM DEPARTMENTS D
 WHERE NOT EXISTS (SELECT 1
 					 FROM EMPLOYEES E
 					WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
; 				

-- IN

-- 사원이 있는 도시를 조회
SELECT *
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID 
 						 FROM DEPARTMENTS
 						WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID
 						  							FROM EMPLOYEES))
;

-- 사원이 없는 도시를 조회
SELECT *
  FROM LOCATIONS 
 WHERE LOCATION_ID NOT IN (SELECT DISTINCT LOCATION_ID
						     FROM DEPARTMENTS
						    WHERE LOCATION_ID IS NOT NULL
						 	  AND DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID 
					 					 			  FROM EMPLOYEES))
;

-- 부서가 없는 국가 (EXISTS)
SELECT *
  FROM COUNTRIES C
 WHERE NOT EXISTS (SELECT 1
 					 FROM LOCATIONS L
 					WHERE L.COUNTRY_ID = C.COUNTRY_ID
 					  AND EXISTS (SELECT 1
 									FROM DEPARTMENTS D
 								   WHERE D.LOCATION_ID = L.LOCATION_ID))
;

-- 부서가 없는 국가 (IN) (부서가 있는 지역이 없는 국가: 결과 맞음)
SELECT *
  FROM COUNTRIES C
 WHERE C.COUNTRY_ID NOT IN (SELECT DISTINCT L.COUNTRY_ID 
 							  FROM LOCATIONS L
 							 WHERE L.LOCATION_ID IN (SELECT DISTINCT D.LOCATION_ID
 							 						   FROM DEPARTMENTS D))
;

-- 부서가 없는 국가 (IN) (부서가 없는 지역이 있는 국가: 결과 틀림)
-- 틀리는 이유: 부서가 없는 지역이 있는 국가에 부서가 있는 지역이 있을 수도 있음 (EXISTS도 마찬가지)
SELECT *
  FROM COUNTRIES C
 WHERE C.COUNTRY_ID IN (SELECT DISTINCT L.COUNTRY_ID 
 						  FROM LOCATIONS L
 						 WHERE L.LOCATION_ID NOT IN (SELECT DISTINCT D.LOCATION_ID
 							 						   FROM DEPARTMENTS D))
;



SELECT DISTINCT EMP.EMPLOYEE_ID
	 , EMP.D
  FROM EMPLOYEES EMP
  JOIN DEP


